---
# tasks file for ssl
- file:
    path: "{{ ssl_cert_path }}"
    state: directory
    owner: "{{ ssl_user }}"
    group: "{{ ssl_group }}"
    mode: "{{ ssl_umask }}"

- copy:
    content: |
            {{ ssl_cert }}
    dest: "{{ ssl_cert_path }}/{{ ssl_crt_name }}"
    owner: "{{ ssl_user }}"
    group: "{{ ssl_group }}"
    mode: "{{ ssl_umask }}"

- copy:
    content: |
            {{ ssl_key }}
    dest: "{{ ssl_cert_path }}/{{ ssl_key_name }}"
    owner: "{{ ssl_user }}"
    group: "{{ ssl_group }}"
    mode: "{{ ssl_umask }}"
