---
# handlers file for ssl
- name: Restart Nginx service Debian or REHL
   service:
     name: nginx
     state: reloaded
     enabled: yes
   when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"  
